"""empty message

Revision ID: 026e8d78ec00
Revises: e11ca7db87b6
Create Date: 2022-11-23 18:50:02.997658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026e8d78ec00'
down_revision = 'e11ca7db87b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rw_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rw_data')
    # ### end Alembic commands ###
